redhat-openstack/rdoinfo

rdo.yml
The latest oslo.utils requires a more recent version of
python-netifaces (> 0.10).
=> Add python-netifaces.

rdo.yml
instack and instack-undercloud have now moved to the rdo-management org
on github for their official source repositories.
=> Replace agroup with rdo-management

rdo.yml
Now required by keystone, packaging here
https://github.com/openstack-packages/python-oslo-log
=> Add oslo-log package

rdo.yml
=> Add python-pysaml2

rdo.yml
We need the latest python-pycadf RPM per recent keystone
dependencies upstream.
=> Add python-pycadf.

rdo.yml
tripleo-puppet-elements is a new project we need to package. Adding to rdo.yml. Can someone also create the repository under openstack-packages and set it up on gerrithub? I'll push up the initial packaging once that's done.
=> Add tripleo-puppet-elements

rdo.yml
This is now required by keystone.
=> Add oslo.policy.

rdo.yml
six is not co-gated upstream, pypi releases are used: six>=1.9.0
Latest release 1.9.0 is avaible in RDO Kilo, also bkabrda pushed
updates in F20-22 https://admin.fedoraproject.org/updates/python-six
=> Do not chase trunk: six

rdo.yml
Each (release, dist) has it's own set of repos available. Having this
information in rdoinfo allows querying available packages and more.
=> distrepos: new release information

rdo.yml
We've had problems with the delorean server becoming inaccessible and have
found a little evidence that it is linked to the build of ironic. Removing
it Temporarily to prove or disprove the theory.
=> Temporarily remove ironic

rdo.yml
When using the lib conf, the master-distgit repo substitution was
wrong for this package.
=> Fix python-django-openstack-auth

rdo.yml
Tripleo needs ironic in this repository in order to keep moving
forward and It looks like ironic didn't cause the problem we were
observing on the delorean server.
This reverts commit 8b1918e8565f5cd297b600063d2d5706fb00330e.
=> Revert "Temporarily remove ironic"

rdo.yml
Add python-manilaclient (all steps done)
```bash
$ delorean --config-file projects.ini --local --package-name python-manilaclient --dev  --info-repo /home/hguemar/rdoinfo/
INFO:delorean:Getting git://git.openstack.org/openstack/python-manilaclient to ./data/python-manilaclient
INFO:delorean:Processing python-manilaclient a30c30f8abe0f9e0fd7f5ed2eaa0d01af34b7ea9
$ ls data/repos/current/              
delorean.repo  installed  python-manilaclient-1.2.0-post7.fc21.noarch.rpm  python-manilaclient-1.2.0-post7.fc21.src.rpm  python-manilaclient-doc-1.2.0-post7.fc21.noarch.rpm  repodata  rpmbuild.log
```
Add myself to notifications for cinder, clients and python libs
=> Add python-manilaclient

rdo.yml
It has moved from stackforge to the openstack tree.
=> Fix location of networking-odl

rdo.yml
Please @flaper87 review changes.
```bash
$ delorean --config-file projects.ini --local --package-name openstack-zaqar --dev  --info-repo /home/hguemar/rdoinfo/    
INFO:delorean:Getting git://github.com/openstack-packages/zaqar to ./data/openstack-zaqar_distro
INFO:delorean:Getting git://git.openstack.org/openstack/zaqar to ./data/openstack-zaqar
INFO:delorean:Processing openstack-zaqar 8919f5af6faaf839a42c0d9c49bf53259cf966ac
$ ls -l data/repos/89/19/8919f5af6faaf839a42c0d9c49bf53259cf966ac_dev/
total 1064
-rw-r--r--. 1 hguemar hguemar    204 Jun 12 23:06 delorean.repo
-rw-r--r--. 1 hguemar hguemar   2063 Jun 12 23:05 distro_delta.diff
-rw-r--r--. 1 hguemar hguemar      0 Jun 12 23:06 installed
-rw-r--r--. 1 hguemar hguemar 451924 Jun 12 23:06 openstack-zaqar-2015.2-dev62.fc21.noarch.rpm …
```
=> Import Zaqar in Delorean

rdo.yml
We'll need to package octavia for the Liberty release.
distro files (and spec among them) can temporarily be found here: https://github.com/nmagnezi/openstack-octavia_distro
=> Adds the octavia package

rdo.yml
This pull request serves as a little more then just updating `rdo.yml`
I've added a spec repo here [networking-cisco-packages](https://github.com/bdemers/networking-cisco-packages) which hopefully would be moved to openstack-packages/python-networking-cisco
Please have a look at both the `rdo.yml` and [networking-cisco-packages](https://github.com/bdemers/networking-cisco-packages) let me know what you think.
**Update:** openstack-packages/python-networking-cisco as added
=> Adding networking-cisco to rdo.yml

rdo.yml
This move was discussed here http://lists.openstack.org/pipermail/openstack-dev/2015-July/070140.html
We're in the process of moving all of these projects upstream under
the tripleo umbrella so they should be the the delorean repository.
Once they are pulled upstream we can remove all the links to the
rdo-management github organization.
=> Pull rdo-manager, instack-undercloud and dep into delorean/master

rdo.yml
neutron now requires a newer version of this than what is in rdo/kilo,
add it explicitly to rdoinfo until we are requiring rdo/liberty.
=> Add python-alembic

rdo.yml
This is now a required dependency for upstream projects like Glance.
=> Add python-castellan.

rdo.yml
Upstream this project has been moved and renamed.
=> Rename rdomanager-oscplugin to tripleoclient

rdo.yml
These have been moved to git.openstack.org.
=> Get instack and instack undercloud from their new homes

rdo.yml
This is a rename of ironic-discoverd for liberty, so we do not need to build ironic-discoverd anymore.
=> Add ironic-inspector to delorean

rdo.yml
Details in https://www.redhat.com/archives/rdo-list/2015-September/msg00164.html
Also rename it to python-* as a first step to sync with Fedora Rawhide.
=> Pin os-client-config to the last known version without keystoneauth dep

rdo.yml
Builds in delorean
```bash
% delorean --config-file projects.ini --package-name python-ceilometermiddleware --info-repo ~/.rdopkg/rdoinfo --local --dev
INFO:delorean:Getting git://git.openstack.org/openstack/ceilometermiddleware to ./data/python-ceilometermiddleware
INFO:delorean:Processing python-ceilometermiddleware 7005d98f47be809243d627cee7ca594390cddec2
% ls -l data/repos/70/05/7005d98f47be809243d627cee7ca594390cddec2_dev/*.rpm(^@)
-rw-r--r--. 1 hguemar hguemar 27004 Sep 19 01:29 data/repos/70/05/7005d98f47be809243d627cee7ca594390cddec2_dev/python-ceilometermiddleware-0.3.0-0.99.20150918.2327git.fc22.noarch.rpm
-rw-r--r--. 1 hguemar hguemar 21696 Sep 19 01:29 data/repos/70/05/7005d98f47be809243d627cee7ca594390cddec2_dev/python-ceilometermiddleware-0.3.0-0.99.20150918.2327git.fc22.src. …
```
=> Add python-ceilometermiddleware

rdo.yml
upstream issue has been fixed in 1.7.4
https://bugs.launchpad.net/os-client-config/+bug/1496689
=> unpin os-client-config

rdo.yml
This is will allow master rdoinfo to be used by Delorean instances
building from stable/* branches by specifying distro= and source=
parameters in projects.ini using proposed Delorean change https://review.gerrithub.io/248584
=> Remove explict distro-branch from rdoinfo

rdo.yml
We need the project name to be tripleo-incubator in order
for the delorean map-project-name script to map the upstream
project name to the rpm package name.
Without this tripleoci is unable to build the openstack-tripleo
package.
=> Fix tripleo-incubator

rdo.yml
Changing the project name for tripleo-incubator to make the
map-packages work, had the unitended consequence of breaking
the distgit urls, since they include the project name when using
conf=core.
=> Fix tripleo-incubator distgit URLs

rdo.yml
It is no longer in stackforge.
=> Move packstack to the openstack namespace

rdo.yml
osprofiler and networking-mlnx are now in the openstack namespace.
Also, networking-bigswitch is no longer maintained, so removing.
=> Complete stackforge to openstack migration

rdo.yml
https://review.gerrithub.io/250647 changed the spec file name from
os-brick.spec to python-os-brick.spec. This was confusing delorean
when executed with --order.
=> Update python-os-brick information

rdo.yml
Builds but doesn't functionally work yet due to missing python2-yaql
>= 1.0.0 dependency. Also, docs are currently disable due to a missing
docs package for sphinxcontrib-pecanswme.
=> Add mistral

rdo.yml
For some reason it was not there yet.
=> Add python-barbicanclient

rdo.yml
rdopkg clone fails due to horizon package having a non-predictible name
=> Fix horizon configuration

rdo.yml
The packaging repo is available here: https://github.com/ObjectifLibre/python-cloudkittyclient
The delorean build with this setup is successful.
=> Add python-cloudkittyclient package

rdo.yml
https://trello.com/c/wzdl1IlZ/52-openstack-in-fedora
* RDO Liberty repo is EL7 only
* distgit moves to openstack-packages rdo-liberty branch
* clients stay in Fedora proper
=> Implement OpenStack in Fedora conclusions

rdo.yml
The openstack-puppet-modules repo has changed its branches to match
the rest of the OpenStack projects, so there is no need to use
master-patches anymore. We now have master and stable/liberty with
the appropriate content.
=> Remove special case for OPM

rdo.yml
Couple open items:
~~1. Package name:
Doc suggests the package name should be 'python-cisco-ironic-contrib' but... to me that implies incorrect ownership.  And does NOT match other openstack naming (networking-*, fuel-plugin-*, etc)
I've named the package python-ironic-cisco, but I'll change it if needed.~~
~~1. Create a spec repo in openstack-packages (once the above issue is resolved)~~
python-ironic-cisco has been imported to: openstack-packages/python-ironic-cisco
=> Adding cisco-ironic-contrib to rdo

rdo.yml
```bash
% delorean --config projects.ini --package-name python-gnocchiclient --local --dev
INFO:delorean:Getting git://github.com/openstack-packages/python-gnocchiclient to ./data/python-gnocchiclient_distro
INFO:delorean:Getting git://git.openstack.org/openstack/python-gnocchiclient to ./data/python-gnocchiclient
INFO:delorean:Processing python-gnocchiclient b32b59d5d581527b742d78995725915dcd02b871
```
=> Add missing gnocchiclient

rdo.yml
Also does not follow stable/liberty branch naming, so override it to
use gnocchi 1.3 branch for Liberty builds.
Depends on Delorean change https://review.gerrithub.io/262359
=> tags: gnocchi is liberty and mitaka only

rdo.yml
Override tags for projects NOT in rdoinfo-Kilo[1]
because default is all tags defined in package-default:
branch overrides are not needed for Kilo packages, special cases were
openstack-puppet-modules and packstack  but they now use standard stable/* branches.
[1] https://github.com/apevec/rdoinfo-Kilo
=> merge rdoinfo-Kilo

rdo.yml
As opposed to Liberty (stable/liberty), the Kilo branch is kilo.
=> Set source-branch for kilo version of OPM

rdo.yml
OPM now has a stable/kilo branch, so tags are no longer needed.
=> Remove OPM tags

rdo.yml
stable/liberty for i-p-a was historical misunderstanding:
http://lists.openstack.org/pipermail/openstack-dev/2016-February/086985.html
=> ironic-python-agent is actually branchless

rdo.yml
Those dependencies are now packaged in Fedora and CentOS Cloud SIG.
=> Drop non-openstack projects

rdo.yml
Now the package will use "master" for master packaging, and "liberty"
for stable/liberty.
=> Set proper branches for Tempest package

rdo.yml
`pradk` apevec, yes 2.0 is mitaka compatible
=> gnocchi 2.0 is mitaka

rdo.yml
Please review @egafford @pdmack @vkmc
```
dlrn --info-repo ~/.rdopkg/rdoinfo --config-file projects.ini  --package-name openstack-sahara-ui
INFO:dlrn:Getting git://github.com/openstack-packages/sahara-dashboard to ./data/openstack-sahara-ui_distro
INFO:dlrn:Getting git://git.openstack.org/openstack/sahara-dashboard to ./data/openstack-sahara-ui
INFO:dlrn:Processing openstack-sahara-ui 466690137f6ee6b4445ee1effd6bd13e87901340
INFO:dlrn:128 packages not built correctly: not updating the consistent symlink
% dlrn --info-repo ~/.rdopkg/rdoinfo --config-file projects.ini  --package-name openstack-trove-ui 
INFO:dlrn:Getting git://github.com/openstack-packages/trove-dashboard to ./data/openstack-trove-ui_distro
INFO:dlrn:Getting git://git.openstack.org/openstack/trove-dashboard to …
```
=> Add trove and sahara dashboard

rdo.yml
Needs to be added everywhere where tags are overriden, which currently
means all packages not present in RDO Kilo.
=> Add newton tags

rdo.yml
Being "lib", its repo would become github.com/openstack/k8sclient. It
needs to be "client", so it is github.com/openstack/python-k8sclient.
=> Set proper conf for k8sclient
