redhat-openstack/rdoinfo

- rdo.yml
Synchronization with the OPM Puppetfile (master-patches)
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>
> [OPM] Puppet Modules repositories synchronization

- rdo.yml
This can be merged when all of https://review.gerrithub.io/#/q/topic:opm-from-master-patches is merged AND running in production!
@yac @strider @derekhiggins @dprince @javierpena @alobbs please review this PR and patches above.
> Opm from master patches

- rdo.yml
> Add oslo-versionedobjects

- rdo.yml
New dependency of openstackclient
> Add os-client-config

- rdo.yml
All appropriate repos in place; tested through basic delorean build locally.
> Adding sahara project configuration

- rdo.yml
Please don't merge until I've double-checked global-requirements on master!
> RFC Drop non-OpenStack projects which are updated in RDO Kilo

- rdo.yml
set rpm-master in conf templates
use project/name variables where possible
./verify.py before/after show no changes
> conf cleanup

- rdo.yml
Signed-off-by: Gael Chamoulaud <gchamoul@redhat.com>
> Add new python-appdirs project

- rdo.yml
See the list of Oslo projects at https://wiki.openstack.org/wiki/Oslo
> debtcollector is part of Oslo

- rdo.yml
Needed for recent version of python-openstackclient
> Adding python-cliff

- rdo.yml
This package includes Neutron driver for VMware NSX controller.
> New package: python-networking-vmware-nsx

- rdo.yml
> Add liberty testing

- rdo.yml
> Fedora 23 has been branched

- rdo.yml
new dep for cliff, adding temporarily while package is under review.
DO NOT import to gerrithub.
> TEMP add unicodecsv

- rdo.yml
> Add networking-bigswitch

- rdoinfo/__init__.py
This commit is adding a check when loading the YAML file, to verify
there are no duplicated projects. Right now, checking for project
name and upstream repo, as this can break Delorean.
> Check for duplicated projects

- rdo.yml
> Add keystoneauth1

- rdo.yml
> Add python-zaqarclient

- rdo.yml
Both rpm-kilo and rpm-master now builds in delorean
Cc @elmiko @apevec
> Add barbican

- rdo.yml
> Fix pyton-os-win package

- rdo.yml
> Add https://wiki.openstack.org/wiki/Oslo#tooz

- rdo.yml
distgit: https://github.com/booxter/python-neutron-lib
> Added neutron-lib package

- rdo.yml
> Fix kilo branch for OPM

- rdo.yml
```bash
delorean --config-file projects.ini --package-name openstack-manila-ui --local
INFO:delorean:Getting git://github.com/openstack-packages/manila-ui to ./data/openstack-manila-ui_distro
INFO:delorean:Getting git://git.openstack.org/openstack/manila-ui to ./data/openstack-manila-ui
INFO:delorean:Processing openstack-manila-ui bf382083b281a77f77df9e0bd51376df49d53b2e
INFO:delorean:131 packages not built correctly: not updating the consistent symlink
```
> Add manila-ui

- rdo.yml
> ironic-lib is Mitaka only

- rdo.yml
NB http://mirror.centos.org/centos/7/cloud/x86_64/openstack-mitaka/
will be available on GA
> Define RDO Mitaka testing
